export { HomeArtistaPage } from './DashboardPage';
export { ArtistServicesPage } from './ArtistServicesPage';
export { ArtistMediaPage } from './ArtistMediaPage';
export { ArtistProfileIdRedirect } from './ArtistProfileIdRedirect';
export { ArtistProfileLayout } from './ArtistProfileLayout';
export { ArtistProfileMainPage } from './ArtistProfileMainPage';
export { ArtistProfileGalleryPage } from './ArtistProfileGalleryPage';
export { ArtistProfileDocumentsPage } from './ArtistProfileDocumentsPage';
export { ArtistCalendarPage } from './ArtistCalendarPage';
